# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:30:20+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Address(BaseModel):
    country: Optional[str] = Field(None, description='Country name component.')
    formatted: Optional[str] = Field(
        None,
        description='Full mailing address, formatted for display or use on a mailing label. This field MAY contain multiple lines, separated by newlines. Newlines can be represented either as a carriage return/line feed pair or as a single line feed character.',
    )
    locality: Optional[str] = Field(None, description='City or locality component.')
    postal_code: Optional[str] = Field(
        None, description='Zip code or postal code component.'
    )
    region: Optional[str] = Field(
        None, description='State, province, prefecture, or region component.'
    )
    street_address: Optional[str] = Field(
        None,
        description='Full street address component, which MAY include house number, street name, post office box, and multi-line extended street address information. This field MAY contain multiple lines, separated by newlines. Newlines can be represented either as a carriage return/line feed pair or as a single line feed character.',
    )


class Client(BaseModel):
    field_id: Optional[str] = Field(
        None, alias='@id', description="URL of the Client's JSON representation."
    )
    client_id: str = Field(..., description='OAuth 2.0 client identifier string.')
    client_name: Optional[str] = Field(
        None,
        description='Human-readable string name of the client to be presented to the end-user during authorization.',
    )
    client_secret: Optional[str] = Field(
        None, description='OAuth 2.0 client secret string. '
    )
    client_uri: Optional[str] = Field(
        None,
        description='URL string of a web page providing information about the client.',
    )
    contacts: Optional[List] = Field(
        None,
        description='Array of strings representing ways to contact people responsible for this client, typically email addresses.',
    )
    grant_types: Optional[List] = Field(
        None,
        description='Array of OAuth 2.0 grant type strings that the client can use at the token endpoint.',
    )
    jwks: Optional[List] = Field(
        None,
        description="Client's JSON Web Key Set [RFC7517] document value, which contains the client's public keys.  The value of this field MUST be a JSON object containing a valid JWK Set.",
    )
    jwks_uri: Optional[str] = Field(
        None,
        description="URL string referencing the client's JSON Web Key (JWK) Set [RFC7517] document, which contains the client's public keys.",
    )
    logo_email: Optional[str] = Field(
        None, description='An email address used to generate a gravatar.com logo_uri.'
    )
    logo_uri: Optional[str] = Field(
        None, description='URL string that references a logo for the client.'
    )
    policy_uri: Optional[str] = Field(
        None,
        description='URL string that points to a human-readable privacy policy document that describes how the deployment organization collects, uses, retains, and discloses personal data.',
    )
    redirect_uris: Optional[List] = Field(
        None,
        description='Array of redirection URI strings for use in redirect-based flows such as the authorization code and implicit flows.',
    )
    response_types: Optional[List] = Field(
        None,
        description='Array of the OAuth 2.0 response type strings that the client can use at the authorization endpoint.',
    )
    scope: Optional[str] = Field(
        None,
        description='String containing a space-separated list of scope values (as described in Section 3.3 of OAuth 2.0 [RFC6749]) that the client can use when requesting access tokens.',
    )
    software_id: Optional[str] = Field(
        None,
        description='A unique identifier string (e.g., a Universally Unique Identifier (UUID)) assigned by the client developer or software publisher used by registration endpoints to identify the client software to be dynamically registered.',
    )
    software_version: Optional[str] = Field(
        None,
        description='A version identifier string for the client software identified by software_id.',
    )
    token_endpoint_auth_method: Optional[str] = Field(
        None,
        description='String indicator of the requested authentication method for the token endpoint.',
    )
    tos_uri: Optional[str] = Field(
        None,
        description='URL string that points to a human-readable terms of service document for the client that describes a contractual relationship between the end-user and the client that the end-user accepts when authorizing the client.',
    )


class Domain(BaseModel):
    field_id: Optional[str] = Field(
        None, alias='@id', description="The URL of the domain's JSON representation."
    )
    logo: Optional[str] = Field(
        None,
        description='The URL of the domain logo. The image from this address is displayed on the webpage of the domain.',
    )
    members: Optional[List] = Field(
        None, description='The tenants included in a domain.'
    )
    name: Optional[str] = Field(None, description='The displayed domain name.')
    profile: Optional[str] = Field(None, description="The URL of the domain's webpage.")
    sub: Optional[str] = Field(
        None,
        description='The fully qualified DNS name of the domain (e.g. phantauth.net).',
    )


class Fleet(BaseModel):
    field_id: Optional[str] = Field(
        None, alias='@id', description="URL of the Fleet's JSON representation."
    )
    logo: Optional[str] = Field(
        None,
        description='The URL of the fleet logo, which can be customized by the gravatar associated with the email address in the `logo_email` property.',
    )
    logo_email: Optional[str] = Field(
        None,
        description='The email address of the fleet, either generated or provided in the `sub` property. The fleet logo can be customized by the use of the gravater associated with this email address.',
    )
    members: Optional[List] = Field(
        None, description='The client objects included in a fleet.'
    )
    name: Optional[str] = Field(None, description='The displayed fleet name.')
    profile: Optional[str] = Field(None, description='The URL of the Fleet profile.')
    sub: str = Field(
        ...,
        description='The name or email address of a given fleet. The fleet properties and fleet members are generated from this name. If provide an email address, you can customize the fleet logo by the use of the gravatar associated with the email address.',
    )


class Team(BaseModel):
    field_id: Optional[str] = Field(
        None, alias='@id', description="URL of the Teams's JSON representation."
    )
    logo: Optional[str] = Field(
        None,
        description='The URL of the team logo, which can be customized by the gravatar associated with the email address in the `logo_email` property.',
    )
    logo_email: Optional[str] = Field(
        None,
        description='The email address of the team, either generated or provided in the `sub` property. The team logo can be customized by the use of the gravater associated with this email address.',
    )
    members: Optional[List] = Field(
        None, description='The user objects that generate a team member.'
    )
    name: Optional[str] = Field(None, description='The displayed team name.')
    profile: Optional[str] = Field(None, description='The URL of the Team profile.')
    sub: str = Field(
        ...,
        description='The name or email address of a given team. The team properties and team members are generated from this name. If you provide an email address, you can customize the team logo by the use of the gravatar associated with the email address.',
    )


class Tenant(BaseModel):
    field_id: Optional[str] = Field(
        None, alias='@id', description="The URL of the tenant's JSON representation."
    )
    about: Optional[str] = Field(
        None,
        description='A detailed description of the tenant. If it takes the value of an URL, the description is downloaded from the given URL, otherwise the value it takes is the description itself. Markdown formatting can be used in the description.',
    )
    attribution: Optional[str] = Field(
        None,
        description='The attribution of the external data source or random user generator. Its value can have markdown formatting, that is, the external source can contain highlights and links.',
    )
    depot: Optional[str] = Field(
        None,
        description="It defines the place of the CSV file containing the resource data in [RFC 6570 - URI temaplate](https://tools.ietf.org/html/rfc6570) format.\nThe URI template receives the type of the object to be generated (user, team) in the `kind` parameter.\n\nThe first line of the CSV file contains the resource property names, the following lines, on the other hand, contain the relevant data.\nIn the case of nested properties, a '.' character separates the elements of the property name (e.g. address.formatted).",
    )
    depots: Optional[List] = Field(
        None,
        description='A list of resource types supported by the external CSV set in `depot`.',
    )
    domain: Optional[bool] = Field(
        None,
        description='True in the case of a domain tenant collecting several tenants, otherwise false.',
    )
    factories: Optional[List] = Field(
        None,
        description='A list of resource types supported by the external generator set in `factory`.',
    )
    factory: Optional[str] = Field(
        None,
        description='The address of the custom random resource generator (user, team) in [RFC 6570 - URI temaplate](https://tools.ietf.org/html/rfc6570) format.\nThe URI template receives the type of the object to be generated (user, team) in the `kind` parameter, and the identifier of the object to be generated in the `name` parameter.',
    )
    favicon: Optional[str] = Field(
        None,
        description="The URL of the tenant favicon. The image from this address appears as a shortcut icon in the browser when a user visits the tenant's webpages.",
    )
    issuer: str = Field(
        ...,
        description='The URL of the tenant OpenID Connect issuer. This value allows you to get, for example, the [OpenID Provider Metadata](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata).\nAs a webpage, it contains information on the use if the given tenant.',
    )
    logo: Optional[str] = Field(
        None,
        description="The URL of the tenant logo. The image from this address appears in the address bar of the tenant's webpages and the pages that contain the list of available tenants.",
    )
    name: Optional[str] = Field(
        None,
        description="The displayed tenant name. In lack of such name, the DNS name of the tenant is displayed in the address bar of the tenant's webpages.",
    )
    script: Optional[str] = Field(
        None,
        description='The URL of a custom JavaScript file can be automatically inserted in the login.html, consent.html, és test.html pages.',
    )
    sheet: Optional[str] = Field(
        None,
        description="It is used to give the identifyer of a public Google Sheet document. The first line of the table contains the user property names, the following lines, on the other hand, contain the relevant data.\nIn the case of nested properties, a '.' character separates the elements of the property name (e.g. address.formatted).",
    )
    sub: str = Field(
        ...,
        description='The fully qualified DNS domain name of the tenant. In the case of official and shared tenants (phantauth.net and phantauth.cf DNS domain), the DNS domain can be omitted (e.g. *default* or *faker*).',
    )
    subtenant: Optional[bool] = Field(
        None,
        description='True in the case of a tenant referred to in a domain tenant, otherwise false.',
    )
    summary: Optional[str] = Field(
        None,
        description="A one-line description, the watchword of the tenant. It appears on the tenant's startup page and the pages that contain the list of available tenants. It takes the valua of an unformatted text.",
    )
    template: Optional[str] = Field(
        None,
        description='It defines the place of the templates of the HTML pages of the tenant in [RFC 6570 - URI temaplate](https://tools.ietf.org/html/rfc6570) format.\nThe URI template receives the page name in a `resource` parameter. By default, it takes the following value: `https://default.phantauth.net{/resource}`.',
    )
    theme: Optional[str] = Field(
        None,
        description="The URL of the CSS style sheet used for the tenant's webpages.\nThe default webpage templates were created by the use of the Bootstrap library, therefore, the Bootstrap CSS URL has to be provided when such a webpage is used.",
    )
    userinfo: Optional[str] = None
    website: Optional[str] = Field(
        None,
        description="The website address associated with the tenant. If a tenant doesn't have a website, its value is identical with that of the `issuer` property.",
    )


class User(BaseModel):
    field_id: Optional[str] = Field(
        None, alias='@id', description="The URL of the user's JSON representation."
    )
    address: Optional[Address] = None
    birthdate: Optional[str] = Field(
        None,
        description="The user's birthday, represented as an ISO 8601:2004 [ISO8601‑2004] YYYY-MM-DD format.",
    )
    email: Optional[str] = Field(
        None, description="The user's preferred email address."
    )
    email_verified: Optional[bool] = Field(
        None,
        description="True if the user's e-mail address has been verified; otherwise false.",
    )
    family_name: Optional[str] = Field(
        None, description="The user's surname(s) or last name(s)."
    )
    gender: Optional[str] = Field(
        None,
        description="The enduser's gender. Possible values are: female, male, and unknown.",
    )
    given_name: Optional[str] = Field(
        None, description="The user's given name(s) or first name(s)."
    )
    locale: Optional[str] = Field(
        None,
        description="The user's locale, represented as a BCP47 [RFC5646] language tag. It is an ISO 639-1 Alpha-2 language code in lowercase and an ISO 3166-1 Alpha-2 country code in uppercase letters, separated by a dash.",
    )
    me: Optional[str] = Field(
        None, description="The simplified URL of the user's profile page."
    )
    middle_name: Optional[str] = Field(None, description="The user's middle name(s).")
    name: Optional[str] = Field(
        None,
        description="The user's full name in displayable form, including all name parts, possibly including titles and suffixes, ordered according to the enduser's locale and preferences.",
    )
    nickname: Optional[str] = Field(
        None,
        description='A casual name of the User that may or may not be the same as the given_name.',
    )
    password: Optional[str] = Field(None, description="The user's generated password.")
    phone_number: Optional[str] = Field(
        None, description="The user's preferred telephone number."
    )
    phone_number_verified: Optional[bool] = Field(
        None,
        description="True if the enduser's phone number has been verified; otherwise false.",
    )
    picture: Optional[str] = Field(
        None, description="The URL of the user's profile picture."
    )
    preferred_username: Optional[str] = Field(
        None,
        description='A shorthand name by which the user wishes to be referred to at the Relying Party.',
    )
    profile: Optional[str] = Field(
        None, description="The URL of the user's profile page."
    )
    sub: str = Field(..., description='Subject - User identifier at the issuer.')
    uid: Optional[str] = Field(
        None, description="The user's simplified, shortened identifier at the Issuer."
    )
    updated_at: Optional[float] = Field(
        None,
        description="The time when the User's information was last updated. Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time.",
    )
    webmail: Optional[str] = Field(
        None, description="The URL of user's mailbox in a webmail application."
    )
    website: Optional[str] = Field(
        None, description="The URL of the user's webpage or blog."
    )
    zoneinfo: Optional[str] = Field(
        None,
        description="A string from the zoneinfo time zone database representing the user's time zone. For example, Europe/Paris or America/Los_Angeles.",
    )


class ClientPostRequest(BaseModel):
    field_id: Optional[str] = Field(
        None, alias='@id', description="URL of the Client's JSON representation."
    )
    client_id: str = Field(..., description='OAuth 2.0 client identifier string.')
    client_name: Optional[str] = Field(
        None,
        description='Human-readable string name of the client to be presented to the end-user during authorization.',
    )
    client_secret: Optional[str] = Field(
        None, description='OAuth 2.0 client secret string. '
    )
    client_uri: Optional[str] = Field(
        None,
        description='URL string of a web page providing information about the client.',
    )
    contacts: Optional[List] = Field(
        None,
        description='Array of strings representing ways to contact people responsible for this client, typically email addresses.',
    )
    grant_types: Optional[List] = Field(
        None,
        description='Array of OAuth 2.0 grant type strings that the client can use at the token endpoint.',
    )
    jwks: Optional[List] = Field(
        None,
        description="Client's JSON Web Key Set [RFC7517] document value, which contains the client's public keys.  The value of this field MUST be a JSON object containing a valid JWK Set.",
    )
    jwks_uri: Optional[str] = Field(
        None,
        description="URL string referencing the client's JSON Web Key (JWK) Set [RFC7517] document, which contains the client's public keys.",
    )
    logo_email: Optional[str] = Field(
        None, description='An email address used to generate a gravatar.com logo_uri.'
    )
    logo_uri: Optional[str] = Field(
        None, description='URL string that references a logo for the client.'
    )
    policy_uri: Optional[str] = Field(
        None,
        description='URL string that points to a human-readable privacy policy document that describes how the deployment organization collects, uses, retains, and discloses personal data.',
    )
    redirect_uris: Optional[List] = Field(
        None,
        description='Array of redirection URI strings for use in redirect-based flows such as the authorization code and implicit flows.',
    )
    response_types: Optional[List] = Field(
        None,
        description='Array of the OAuth 2.0 response type strings that the client can use at the authorization endpoint.',
    )
    scope: Optional[str] = Field(
        None,
        description='String containing a space-separated list of scope values (as described in Section 3.3 of OAuth 2.0 [RFC6749]) that the client can use when requesting access tokens.',
    )
    software_id: Optional[str] = Field(
        None,
        description='A unique identifier string (e.g., a Universally Unique Identifier (UUID)) assigned by the client developer or software publisher used by registration endpoints to identify the client software to be dynamically registered.',
    )
    software_version: Optional[str] = Field(
        None,
        description='A version identifier string for the client software identified by software_id.',
    )
    token_endpoint_auth_method: Optional[str] = Field(
        None,
        description='String indicator of the requested authentication method for the token endpoint.',
    )
    tos_uri: Optional[str] = Field(
        None,
        description='URL string that points to a human-readable terms of service document for the client that describes a contractual relationship between the end-user and the client that the end-user accepts when authorizing the client.',
    )


class ClientClientIdGetResponse(BaseModel):
    field_id: Optional[str] = Field(
        None, alias='@id', description="URL of the Client's JSON representation."
    )
    client_id: str = Field(..., description='OAuth 2.0 client identifier string.')
    client_name: Optional[str] = Field(
        None,
        description='Human-readable string name of the client to be presented to the end-user during authorization.',
    )
    client_secret: Optional[str] = Field(
        None, description='OAuth 2.0 client secret string. '
    )
    client_uri: Optional[str] = Field(
        None,
        description='URL string of a web page providing information about the client.',
    )
    contacts: Optional[List] = Field(
        None,
        description='Array of strings representing ways to contact people responsible for this client, typically email addresses.',
    )
    grant_types: Optional[List] = Field(
        None,
        description='Array of OAuth 2.0 grant type strings that the client can use at the token endpoint.',
    )
    jwks: Optional[List] = Field(
        None,
        description="Client's JSON Web Key Set [RFC7517] document value, which contains the client's public keys.  The value of this field MUST be a JSON object containing a valid JWK Set.",
    )
    jwks_uri: Optional[str] = Field(
        None,
        description="URL string referencing the client's JSON Web Key (JWK) Set [RFC7517] document, which contains the client's public keys.",
    )
    logo_email: Optional[str] = Field(
        None, description='An email address used to generate a gravatar.com logo_uri.'
    )
    logo_uri: Optional[str] = Field(
        None, description='URL string that references a logo for the client.'
    )
    policy_uri: Optional[str] = Field(
        None,
        description='URL string that points to a human-readable privacy policy document that describes how the deployment organization collects, uses, retains, and discloses personal data.',
    )
    redirect_uris: Optional[List] = Field(
        None,
        description='Array of redirection URI strings for use in redirect-based flows such as the authorization code and implicit flows.',
    )
    response_types: Optional[List] = Field(
        None,
        description='Array of the OAuth 2.0 response type strings that the client can use at the authorization endpoint.',
    )
    scope: Optional[str] = Field(
        None,
        description='String containing a space-separated list of scope values (as described in Section 3.3 of OAuth 2.0 [RFC6749]) that the client can use when requesting access tokens.',
    )
    software_id: Optional[str] = Field(
        None,
        description='A unique identifier string (e.g., a Universally Unique Identifier (UUID)) assigned by the client developer or software publisher used by registration endpoints to identify the client software to be dynamically registered.',
    )
    software_version: Optional[str] = Field(
        None,
        description='A version identifier string for the client software identified by software_id.',
    )
    token_endpoint_auth_method: Optional[str] = Field(
        None,
        description='String indicator of the requested authentication method for the token endpoint.',
    )
    tos_uri: Optional[str] = Field(
        None,
        description='URL string that points to a human-readable terms of service document for the client that describes a contractual relationship between the end-user and the client that the end-user accepts when authorizing the client.',
    )


class Kind(Enum):
    field_registration_ = '\'registration\''
    field_selfie_ = '\'selfie\''
    field_plain_ = '\'plain\''


class DomainDomainnameGetResponse(BaseModel):
    field_id: Optional[str] = Field(
        None, alias='@id', description="The URL of the domain's JSON representation."
    )
    logo: Optional[str] = Field(
        None,
        description='The URL of the domain logo. The image from this address is displayed on the webpage of the domain.',
    )
    members: Optional[List] = Field(
        None, description='The tenants included in a domain.'
    )
    name: Optional[str] = Field(None, description='The displayed domain name.')
    profile: Optional[str] = Field(None, description="The URL of the domain's webpage.")
    sub: Optional[str] = Field(
        None,
        description='The fully qualified DNS name of the domain (e.g. phantauth.net).',
    )


class FleetFleetnameGetResponse(BaseModel):
    field_id: Optional[str] = Field(
        None, alias='@id', description="URL of the Fleet's JSON representation."
    )
    logo: Optional[str] = Field(
        None,
        description='The URL of the fleet logo, which can be customized by the gravatar associated with the email address in the `logo_email` property.',
    )
    logo_email: Optional[str] = Field(
        None,
        description='The email address of the fleet, either generated or provided in the `sub` property. The fleet logo can be customized by the use of the gravater associated with this email address.',
    )
    members: Optional[List] = Field(
        None, description='The client objects included in a fleet.'
    )
    name: Optional[str] = Field(None, description='The displayed fleet name.')
    profile: Optional[str] = Field(None, description='The URL of the Fleet profile.')
    sub: str = Field(
        ...,
        description='The name or email address of a given fleet. The fleet properties and fleet members are generated from this name. If provide an email address, you can customize the fleet logo by the use of the gravatar associated with the email address.',
    )


class TeamTeamnameGetResponse(BaseModel):
    field_id: Optional[str] = Field(
        None, alias='@id', description="URL of the Teams's JSON representation."
    )
    logo: Optional[str] = Field(
        None,
        description='The URL of the team logo, which can be customized by the gravatar associated with the email address in the `logo_email` property.',
    )
    logo_email: Optional[str] = Field(
        None,
        description='The email address of the team, either generated or provided in the `sub` property. The team logo can be customized by the use of the gravater associated with this email address.',
    )
    members: Optional[List] = Field(
        None, description='The user objects that generate a team member.'
    )
    name: Optional[str] = Field(None, description='The displayed team name.')
    profile: Optional[str] = Field(None, description='The URL of the Team profile.')
    sub: str = Field(
        ...,
        description='The name or email address of a given team. The team properties and team members are generated from this name. If you provide an email address, you can customize the team logo by the use of the gravatar associated with the email address.',
    )


class TenantTenantnameGetResponse(BaseModel):
    field_id: Optional[str] = Field(
        None, alias='@id', description="The URL of the tenant's JSON representation."
    )
    about: Optional[str] = Field(
        None,
        description='A detailed description of the tenant. If it takes the value of an URL, the description is downloaded from the given URL, otherwise the value it takes is the description itself. Markdown formatting can be used in the description.',
    )
    attribution: Optional[str] = Field(
        None,
        description='The attribution of the external data source or random user generator. Its value can have markdown formatting, that is, the external source can contain highlights and links.',
    )
    depot: Optional[str] = Field(
        None,
        description="It defines the place of the CSV file containing the resource data in [RFC 6570 - URI temaplate](https://tools.ietf.org/html/rfc6570) format.\nThe URI template receives the type of the object to be generated (user, team) in the `kind` parameter.\n\nThe first line of the CSV file contains the resource property names, the following lines, on the other hand, contain the relevant data.\nIn the case of nested properties, a '.' character separates the elements of the property name (e.g. address.formatted).",
    )
    depots: Optional[List] = Field(
        None,
        description='A list of resource types supported by the external CSV set in `depot`.',
    )
    domain: Optional[bool] = Field(
        None,
        description='True in the case of a domain tenant collecting several tenants, otherwise false.',
    )
    factories: Optional[List] = Field(
        None,
        description='A list of resource types supported by the external generator set in `factory`.',
    )
    factory: Optional[str] = Field(
        None,
        description='The address of the custom random resource generator (user, team) in [RFC 6570 - URI temaplate](https://tools.ietf.org/html/rfc6570) format.\nThe URI template receives the type of the object to be generated (user, team) in the `kind` parameter, and the identifier of the object to be generated in the `name` parameter.',
    )
    favicon: Optional[str] = Field(
        None,
        description="The URL of the tenant favicon. The image from this address appears as a shortcut icon in the browser when a user visits the tenant's webpages.",
    )
    issuer: str = Field(
        ...,
        description='The URL of the tenant OpenID Connect issuer. This value allows you to get, for example, the [OpenID Provider Metadata](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata).\nAs a webpage, it contains information on the use if the given tenant.',
    )
    logo: Optional[str] = Field(
        None,
        description="The URL of the tenant logo. The image from this address appears in the address bar of the tenant's webpages and the pages that contain the list of available tenants.",
    )
    name: Optional[str] = Field(
        None,
        description="The displayed tenant name. In lack of such name, the DNS name of the tenant is displayed in the address bar of the tenant's webpages.",
    )
    script: Optional[str] = Field(
        None,
        description='The URL of a custom JavaScript file can be automatically inserted in the login.html, consent.html, és test.html pages.',
    )
    sheet: Optional[str] = Field(
        None,
        description="It is used to give the identifyer of a public Google Sheet document. The first line of the table contains the user property names, the following lines, on the other hand, contain the relevant data.\nIn the case of nested properties, a '.' character separates the elements of the property name (e.g. address.formatted).",
    )
    sub: str = Field(
        ...,
        description='The fully qualified DNS domain name of the tenant. In the case of official and shared tenants (phantauth.net and phantauth.cf DNS domain), the DNS domain can be omitted (e.g. *default* or *faker*).',
    )
    subtenant: Optional[bool] = Field(
        None,
        description='True in the case of a tenant referred to in a domain tenant, otherwise false.',
    )
    summary: Optional[str] = Field(
        None,
        description="A one-line description, the watchword of the tenant. It appears on the tenant's startup page and the pages that contain the list of available tenants. It takes the valua of an unformatted text.",
    )
    template: Optional[str] = Field(
        None,
        description='It defines the place of the templates of the HTML pages of the tenant in [RFC 6570 - URI temaplate](https://tools.ietf.org/html/rfc6570) format.\nThe URI template receives the page name in a `resource` parameter. By default, it takes the following value: `https://default.phantauth.net{/resource}`.',
    )
    theme: Optional[str] = Field(
        None,
        description="The URL of the CSS style sheet used for the tenant's webpages.\nThe default webpage templates were created by the use of the Bootstrap library, therefore, the Bootstrap CSS URL has to be provided when such a webpage is used.",
    )
    userinfo: Optional[str] = None
    website: Optional[str] = Field(
        None,
        description="The website address associated with the tenant. If a tenant doesn't have a website, its value is identical with that of the `issuer` property.",
    )


class UserPostRequest(BaseModel):
    field_id: Optional[str] = Field(
        None, alias='@id', description="The URL of the user's JSON representation."
    )
    address: Optional[Address] = Field(
        None, description="The user's preferred postal address."
    )
    birthdate: Optional[str] = Field(
        None,
        description="The user's birthday, represented as an ISO 8601:2004 [ISO8601‑2004] YYYY-MM-DD format.",
    )
    email: Optional[str] = Field(
        None, description="The user's preferred email address."
    )
    email_verified: Optional[bool] = Field(
        None,
        description="True if the user's e-mail address has been verified; otherwise false.",
    )
    family_name: Optional[str] = Field(
        None, description="The user's surname(s) or last name(s)."
    )
    gender: Optional[str] = Field(
        None,
        description="The enduser's gender. Possible values are: female, male, and unknown.",
    )
    given_name: Optional[str] = Field(
        None, description="The user's given name(s) or first name(s)."
    )
    locale: Optional[str] = Field(
        None,
        description="The user's locale, represented as a BCP47 [RFC5646] language tag. It is an ISO 639-1 Alpha-2 language code in lowercase and an ISO 3166-1 Alpha-2 country code in uppercase letters, separated by a dash.",
    )
    me: Optional[str] = Field(
        None, description="The simplified URL of the user's profile page."
    )
    middle_name: Optional[str] = Field(None, description="The user's middle name(s).")
    name: Optional[str] = Field(
        None,
        description="The user's full name in displayable form, including all name parts, possibly including titles and suffixes, ordered according to the enduser's locale and preferences.",
    )
    nickname: Optional[str] = Field(
        None,
        description='A casual name of the User that may or may not be the same as the given_name.',
    )
    password: Optional[str] = Field(None, description="The user's generated password.")
    phone_number: Optional[str] = Field(
        None, description="The user's preferred telephone number."
    )
    phone_number_verified: Optional[bool] = Field(
        None,
        description="True if the enduser's phone number has been verified; otherwise false.",
    )
    picture: Optional[str] = Field(
        None, description="The URL of the user's profile picture."
    )
    preferred_username: Optional[str] = Field(
        None,
        description='A shorthand name by which the user wishes to be referred to at the Relying Party.',
    )
    profile: Optional[str] = Field(
        None, description="The URL of the user's profile page."
    )
    sub: str = Field(..., description='Subject - User identifier at the issuer.')
    uid: Optional[str] = Field(
        None, description="The user's simplified, shortened identifier at the Issuer."
    )
    updated_at: Optional[float] = Field(
        None,
        description="The time when the User's information was last updated. Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time.",
    )
    webmail: Optional[str] = Field(
        None, description="The URL of user's mailbox in a webmail application."
    )
    website: Optional[str] = Field(
        None, description="The URL of the user's webpage or blog."
    )
    zoneinfo: Optional[str] = Field(
        None,
        description="A string from the zoneinfo time zone database representing the user's time zone. For example, Europe/Paris or America/Los_Angeles.",
    )


class UserUsernameGetResponse(BaseModel):
    field_id: Optional[str] = Field(
        None, alias='@id', description="The URL of the user's JSON representation."
    )
    address: Optional[Address] = Field(
        None, description="The user's preferred postal address."
    )
    birthdate: Optional[str] = Field(
        None,
        description="The user's birthday, represented as an ISO 8601:2004 [ISO8601‑2004] YYYY-MM-DD format.",
    )
    email: Optional[str] = Field(
        None, description="The user's preferred email address."
    )
    email_verified: Optional[bool] = Field(
        None,
        description="True if the user's e-mail address has been verified; otherwise false.",
    )
    family_name: Optional[str] = Field(
        None, description="The user's surname(s) or last name(s)."
    )
    gender: Optional[str] = Field(
        None,
        description="The enduser's gender. Possible values are: female, male, and unknown.",
    )
    given_name: Optional[str] = Field(
        None, description="The user's given name(s) or first name(s)."
    )
    locale: Optional[str] = Field(
        None,
        description="The user's locale, represented as a BCP47 [RFC5646] language tag. It is an ISO 639-1 Alpha-2 language code in lowercase and an ISO 3166-1 Alpha-2 country code in uppercase letters, separated by a dash.",
    )
    me: Optional[str] = Field(
        None, description="The simplified URL of the user's profile page."
    )
    middle_name: Optional[str] = Field(None, description="The user's middle name(s).")
    name: Optional[str] = Field(
        None,
        description="The user's full name in displayable form, including all name parts, possibly including titles and suffixes, ordered according to the enduser's locale and preferences.",
    )
    nickname: Optional[str] = Field(
        None,
        description='A casual name of the User that may or may not be the same as the given_name.',
    )
    password: Optional[str] = Field(None, description="The user's generated password.")
    phone_number: Optional[str] = Field(
        None, description="The user's preferred telephone number."
    )
    phone_number_verified: Optional[bool] = Field(
        None,
        description="True if the enduser's phone number has been verified; otherwise false.",
    )
    picture: Optional[str] = Field(
        None, description="The URL of the user's profile picture."
    )
    preferred_username: Optional[str] = Field(
        None,
        description='A shorthand name by which the user wishes to be referred to at the Relying Party.',
    )
    profile: Optional[str] = Field(
        None, description="The URL of the user's profile page."
    )
    sub: str = Field(..., description='Subject - User identifier at the issuer.')
    uid: Optional[str] = Field(
        None, description="The user's simplified, shortened identifier at the Issuer."
    )
    updated_at: Optional[float] = Field(
        None,
        description="The time when the User's information was last updated. Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time.",
    )
    webmail: Optional[str] = Field(
        None, description="The URL of user's mailbox in a webmail application."
    )
    website: Optional[str] = Field(
        None, description="The URL of the user's webpage or blog."
    )
    zoneinfo: Optional[str] = Field(
        None,
        description="A string from the zoneinfo time zone database representing the user's time zone. For example, Europe/Paris or America/Los_Angeles.",
    )


class Kind1(Enum):
    field_access_ = '\'access\''
    field_refresh_ = '\'refresh\''
    field_authorization_ = '\'authorization\''
    field_id_ = '\'id\''
    field_selfie_ = '\'selfie\''
    field_plain_ = '\'plain\''
